##数据源配置
spring:
  datasource:
    url: jdbc:mysql://10.11.117.81:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    name: smart-factory
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 10.11.117.81
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0

##Mybatis 配置
mybatis:
  type-aliases-package: smart.factory.domain
  mapper-locations: classpath:mapper/*.xml

##修改tomcat端口
server:
  port: 8888

  ##日志打印级别
logging:
  level: debug

debug: true




